import 'package:get_it/get_it.dart';
import 'package:dio/dio.dart';
import 'package:mediconsult/core/network/dio_factory.dart';
import 'package:mediconsult/core/services/language_service.dart';
import 'package:mediconsult/features/auth/login/presentation/logic/login_cubit.dart';
import 'package:mediconsult/features/auth/login/presentation/logic/reset_password/cubit/resend_otp_cubit.dart';
import 'package:mediconsult/features/auth/login/presentation/logic/reset_password/cubit/reset_password_cubit.dart';
import 'package:mediconsult/features/auth/login/presentation/logic/reset_password/cubit/send_otp_cubit.dart';
import 'package:mediconsult/features/auth/login/presentation/logic/reset_password/cubit/verify_otp_cubit.dart';
import 'package:mediconsult/features/auth/login/repository/reset_password_repository.dart';
import 'package:mediconsult/features/auth/login/service/login_api_service.dart';
import 'package:mediconsult/features/auth/login/repository/login_repository.dart';
import 'package:mediconsult/features/auth/login/service/reset_password_api_service.dart';
import 'package:mediconsult/features/auth/signup/presentation/logic/signup_cubit.dart';
import 'package:mediconsult/features/auth/signup/repository/register_repository.dart';
import 'package:mediconsult/features/auth/signup/service/register_api_service.dart';
import 'package:mediconsult/features/family_members/presentation/cubit/family_members_cubit.dart';
import 'package:mediconsult/features/family_members/repository/family_member_repo.dart';
import 'package:mediconsult/features/family_members/service/family_member_api_service.dart';
import 'package:mediconsult/features/home/presentation/cubit/cubit/home_cubit.dart';
import 'package:mediconsult/features/home/repository/home_repository.dart';
import 'package:mediconsult/features/home/service/home_api_service.dart';
import 'package:mediconsult/features/profile/presentation/cubit/language_cubit.dart';
import 'package:mediconsult/features/providers/presentation/cubit/providers_cubit.dart';
import 'package:mediconsult/features/providers/service/providers_api_service.dart';
import 'package:mediconsult/features/providers/repository/providers_repository.dart';
import 'package:mediconsult/features/approval_request/service/approval_request_api_service.dart';
import 'package:mediconsult/features/approval_request/repository/approval_request_repository.dart';
import 'package:mediconsult/features/approval_request/presentation/cubit/approval_request_cubit.dart';
import 'package:mediconsult/features/approval_request/repository/approvals_repository.dart';
import 'package:mediconsult/features/approval_request/presentation/cubit/approvals_cubit.dart';
import 'package:mediconsult/features/notifications/service/notification_service.dart';
import 'package:mediconsult/features/notifications/repository/notification_repository.dart';
import 'package:mediconsult/features/notifications/presentation/cubit/notifications_cubit.dart';
import 'package:mediconsult/features/network/service/network_api_service.dart';
import 'package:mediconsult/features/network/repository/network_repository.dart';
import 'package:mediconsult/features/network/logic/network_cubit.dart';
import 'package:mediconsult/features/refund/presentation/cubit/refund_reasons_cubit.dart';
import 'package:mediconsult/features/refund/presentation/cubit/refund_request_cubit.dart';
import 'package:mediconsult/features/refund/presentation/cubit/refund_types_cubit.dart';
import 'package:mediconsult/features/refund/presentation/cubit/refunds_cubit.dart';
import 'package:mediconsult/features/policy/service/get_policy_categories.dart';
import 'package:mediconsult/features/policy/repository/get_policy_categories_repo.dart';
import 'package:mediconsult/features/policy/presentation/cubit/get_policy_categories_cubit.dart';
import 'package:mediconsult/features/policy/service/get_policy_details.dart';
import 'package:mediconsult/features/policy/repository/get_policy_details_repo.dart';
import 'package:mediconsult/features/policy/presentation/cubit/get_policy_details_cubit.dart';
import 'package:mediconsult/features/refund/repository/refund_repository.dart';
import 'package:mediconsult/features/refund/service/refund_api_service.dart';
import 'package:mediconsult/features/support/service/support_api_service.dart';
import 'package:mediconsult/features/support/repository/support_repository.dart';
import 'package:mediconsult/features/support/presentation/cubit/contact_cubit.dart';
import 'package:mediconsult/features/support/presentation/cubit/faq_cubit.dart';
import 'package:mediconsult/features/profile/service/profile_api_service.dart';
import 'package:mediconsult/features/profile/repository/profile_repository.dart';
import 'package:mediconsult/features/profile/repository/change_password_repository.dart';
import 'package:mediconsult/features/profile/presentation/cubit/personal_info_cubit.dart';
import 'package:mediconsult/features/profile/presentation/cubit/change_password_cubit.dart';
import 'package:mediconsult/features/terms_policy/service/terms_api_service.dart';
import 'package:mediconsult/features/terms_policy/repository/terms_repository.dart';
import 'package:mediconsult/features/terms_policy/presentation/cubit/terms_cubit.dart';

final GetIt sl = GetIt.instance;

Future<void> setupServiceLocator() async {
  final Dio dio = await DioFactory.getDio();
  // Services
  sl.registerLazySingleton<LoginApiService>(() => LoginApiService(dio));
  sl.registerLazySingleton<RegisterApiService>(() => RegisterApiService(dio));
  sl.registerLazySingleton<ResetPasswordApiService>(() => ResetPasswordApiService(dio));
  sl.registerLazySingleton<HomeApiService>(() => HomeApiService(dio));
  sl.registerLazySingleton<ProvidersApiService>(() => ProvidersApiService(dio));
  sl.registerLazySingleton<FamilyMemberApiService>(() => FamilyMemberApiService(dio));
  sl.registerLazySingleton<ApprovalRequestApiService>(() => ApprovalRequestApiService(dio));
  sl.registerLazySingleton<NotificationService>(() => NotificationService(dio));
  sl.registerLazySingleton<NetworkApiService>(() => NetworkApiService(dio));
  sl.registerLazySingleton<LanguageService>(() => LanguageService());
  sl.registerLazySingleton<GetPolicyCategoriesApiService>(() => GetPolicyCategoriesApiService(dio));
  sl.registerLazySingleton<GetPolicyDetailsApiService>(() => GetPolicyDetailsApiService(dio));
  sl.registerLazySingleton<SupportApiService>(() => SupportApiService(dio));
  sl.registerLazySingleton<ProfileApiService>(() => ProfileApiService(dio));
  sl.registerLazySingleton<TermsApiService>(() => TermsApiService(dio));
  sl.registerLazySingleton<RefundApiService>(() => RefundApiService(dio));

  // Repositories
  sl.registerLazySingleton<LoginRepository>(() => LoginRepository(sl()));
  sl.registerLazySingleton<ProvidersRepository>(() => ProvidersRepository(sl()));
  sl.registerLazySingleton<RegisterRepository>(() => RegisterRepository(sl()));
  sl.registerLazySingleton<ResetPasswordRepository>(() => ResetPasswordRepository(sl()));
  sl.registerLazySingleton<HomeRepository>(() => HomeRepository(sl()));
  sl.registerLazySingleton<FamilyMemberRepository>(() => FamilyMemberRepository(sl()));
  sl.registerLazySingleton<ApprovalRequestRepository>(() => ApprovalRequestRepository(sl()));
  sl.registerLazySingleton<ApprovalsRepository>(() => ApprovalsRepository(sl()));
  sl.registerLazySingleton<NotificationRepository>(() => NotificationRepository(sl()));
  sl.registerLazySingleton<NetworkRepository>(() => NetworkRepository(sl()));
  sl.registerLazySingleton<GetPolicyCategoriesRepository>(() => GetPolicyCategoriesRepository(sl()));
  sl.registerLazySingleton<GetPolicyDetailsRepository>(() => GetPolicyDetailsRepository(sl()));
  sl.registerLazySingleton<SupportRepository>(() => SupportRepository(sl()));
  sl.registerLazySingleton<ProfileRepository>(() => ProfileRepository(sl()));
  sl.registerLazySingleton<ChangePasswordRepository>(() => ChangePasswordRepository(sl()));
  sl.registerLazySingleton<TermsRepository>(() => TermsRepository(sl()));
  sl.registerLazySingleton<RefundRepository>(() => RefundRepository(sl()));
  // Cubits
  sl.registerFactory<LoginCubit>(() => LoginCubit(sl()));
  sl.registerFactory<SignupCubit>(() => SignupCubit(sl()));
  sl.registerFactory<SendOtpCubit>(() => SendOtpCubit(sl()));
  sl.registerFactory<ResetPasswordCubit>(() => ResetPasswordCubit(sl()));
  sl.registerFactory<ResendOtpCubit>(() => ResendOtpCubit(sl()));
  sl.registerFactory<VerifyOtpCubit>(() => VerifyOtpCubit(sl()));
  sl.registerFactory<HomeCubit>(() => HomeCubit(sl()));
  sl.registerFactory<ProvidersCubit>(() => ProvidersCubit(sl()));
  sl.registerFactory<FamilyMembersCubit>(() => FamilyMembersCubit(sl()));
  sl.registerFactory<ApprovalRequestCubit>(() => ApprovalRequestCubit(sl()));
  sl.registerFactory<ApprovalsCubit>(() => ApprovalsCubit(sl()));
  sl.registerFactory<NotificationsCubit>(() => NotificationsCubit(sl()));
  sl.registerFactory<NetworkCubit>(() => NetworkCubit(sl()));
  sl.registerFactory<RefundsCubit>(() => RefundsCubit(sl()));
  sl.registerFactory<LanguageCubit>(() => LanguageCubit(sl()));
  sl.registerFactory<GetPolicyCategoriesCubit>(() => GetPolicyCategoriesCubit(sl()));
  sl.registerFactory<GetPolicyDetailsCubit>(() => GetPolicyDetailsCubit(sl()));
  sl.registerFactory<ContactCubit>(() => ContactCubit(sl()));
  sl.registerFactory<FaqCubit>(() => FaqCubit(sl()));
  sl.registerFactory<PersonalInfoCubit>(() => PersonalInfoCubit(sl()));
  sl.registerFactory<ChangePasswordCubit>(() => ChangePasswordCubit(sl()));
  sl.registerFactory<TermsCubit>(() => TermsCubit(sl()));
  sl.registerFactory<RefundTypesCubit>(() => RefundTypesCubit(sl()));
  sl.registerFactory<RefundReasonsCubit>(() => RefundReasonsCubit(sl()));
  sl.registerFactory<RefundRequestCubit>(() => RefundRequestCubit(sl()));
}